/* ===== build.js — bundle the ES-module source into a single-file index.html
   ---------------------------------------------------------------------------
   dev.html   : source of truth for the HTML shell. Loads ./src/main.js as a
                real ES module — use this (over any HTTP server) during dev,
                no build step needed.
   index.html : GENERATED. dev.html with the module <script> replaced by the
                whole game bundled inline (esbuild, IIFE). Self-contained, so
                it works from file:// double-click, GitHub Pages, itch.io zip,
                anywhere. Do not edit by hand.

   Usage: node build.js            (add --minify for a smaller artifact)
*/
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'fs';

const minify = process.argv.includes('--minify');

const result = await build({
  entryPoints: ['src/main.js'],
  bundle: true,
  format: 'iife',
  minify,
  write: false,
  target: ['es2019'],
  legalComments: 'none',
});

const js = result.outputFiles[0].text;

const shell = readFileSync('dev.html', 'utf8');
const TAG = '<script type="module" src="./src/main.js"></script>';
if (!shell.includes(TAG)) {
  console.error('build.js: could not find the module script tag in dev.html');
  process.exit(1);
}

const banner = '<!-- GENERATED by build.js — edit dev.html + src/, then run: node build.js -->\n';
/* function form: a plain-string replacement would reinterpret "$&", "$'" etc.
   inside the minified JS as replace() substitution patterns and corrupt the
   bundle (this actually happened once the code first contained a "$&"). */
const html = banner + shell.replace(TAG, () => '<script>\n' + js + '</script>');

writeFileSync('index.html', html);
console.log(`index.html written (${(html.length / 1024).toFixed(1)} kB${minify ? ', minified' : ''})`);
